#ifndef SLOWCRYPT_H
#define SLOWCRYPT_H

#define SLOWCRYPT_STATICALLY_LINKED
#include "chacha20.h"
#include "poly1305.h"
#include "sha3.h"

#include "aed.h"

typedef enum {
    SLOWCRYPT_ALGO_FIRST_HASH,
    SLOWCRYPT_ALGO_FIRST_KECCAK = SLOWCRYPT_ALGO_FIRST_HASH,
    SLOWCRYPT_SHA3_224 = SLOWCRYPT_ALGO_FIRST_KECCAK,
    SLOWCRYPT_SHA3_256,
    SLOWCRYPT_SHA3_384,
    SLOWCRYPT_SHA3_512,
    SLOWCRYPT_SHAKE128,
    SLOWCRYPT_SHAKE256,
    SLOWCRYPT_ALGO_LAST_KECCAK = SLOWCRYPT_SHAKE256,
    SLOWCRYPT_ALGO_LAST_HASH = SLOWCRYPT_ALGO_LAST_KECCAK,
} slowcrypt_algo;

#endif
